### ISSUE TITLE
Workers are extremely slow to start

### ISSUE THREAD

**Issue by lanougue** [dask/dask-jobqueue#193]
Hi everyone,
I play with a PBS cluster but each time I start a cluster, it takes more than 10 minutes to initiate.
Each node have 28 processors and I start 10 nodes = 280 workers (mono-thread)

My code is quite simple

```
cluster = PBSCluster()
cluster.start_workers(10)
client = Client(cluster)
```

Then, I use a home-made function to monitor how many workers are actually started

```
def wait_client_ready(client):
    """
    Wait for the client to be ready (all workers started)
    """
    import time, sys
    Nnodes = len(client.cluster.jobs)
    total_Nw = client.cluster.worker_processes*Nnodes
    Nw = 0.
    while(len(client._scheduler_identity.get('workers', {}))<total_Nw):
        p = len(client._scheduler_identity.get('workers', {}))/total_Nw
        time.sleep(2)
        if p>=Nw:
            Nw = int(p*10)/10
            print('{} % of the workers started'.format(int(p*100)))
            Nw+=0.1
    print('100 % of the workers started: {} workers'.format(total_Nw))

```

The first three lines are instantaneous and qstat on the frontal of my HPC shows that PBS gave me the 10 nodes I required (running status).
Then, the starting procedure of the workers is very slow: My monitoring function shows a relatively fast apparition of the first 50 % of the workers and then it takes a very long time to have the remaining 50 % (especially the last 10 %)

Here is my yaml config file:

```
  pbs:
    name: dask-worker

    # Dask worker options
    cores: 28       
    processes: 28   
    memory: 120GB
    interface: ib0
    death-timeout: 900 # should be large if many workers are launched
    local-directory: null

    # PBS resource manager options
    queue: mpi_1
    project: SKIM
    walltime: '48:00:00'
    extra: ""
    env-extra: []
    resource-spec: select=1:ncpus=28:mem=120GB
    job-extra: ['-m n']
```

Any idea of what could slow down the starting procedure of the workers ?
