### ISSUE TITLE
PBSCluster does not start

### ISSUE THREAD

**Issue by dennissergeev** [dask/dask-jobqueue#216]
Hi,

I've been trying to use dask with dask-jobqueue on an HPC cluster that uses PBS scheduling, but I can't make it to start the processes. I'm following the steps shown in the ["Dask on HPC Introduction"](https://www.youtube.com/watch?v=FXsgmwpRExM).

Essentially, my steps are:
```python
from dask_jobqueue import PBSCluster
from dask.distributed import Client

cluster = PBSCluster(memory="1GB",
                                  resource_spec='select=1:ncpus=36:mem=1000mb',
                                  cores=36)
# (with appropriate queue and project options from yml file)
# also, changing memory keywords doesn't seem to help
```
Then, if I print `cluster`, I get
```python
PBSCluster(cores=0, memory=0 B, workers=0/0, jobs=0/0)
```
which probably means that submission fails, right?

However, when I manually do `qsub job_script.sh` where `job_script.sh` contains the output of `print(cluster.job_script())`, the job is submitted without errors and I can see it in the queue.

So I'm a bit stuck here. Any help would be greatly appreciated please.

Many thanks,
Denis

**Comment by guillaumeeb** [comment]
Hi,

Can you give all the steps you are following, all the python commands?

In particular, may I ask if you actually called `cluster.scale(x)` function, as you did not mention it?

I also encourage you to read https://jobqueue.dask.org/en/latest/debug.html if not already done too.

**Comment by guillaumeeb** [comment]
Can you see the 10 pending jobs in PBS using qstat?

**Comment by dennissergeev** [comment]
Yes. They are initially queuing, then running, but after a minute or so they exit

**Comment by guillaumeeb** [comment]
Can you retrieve the stdout and stderr of one of the job, to see if there is a problem?

What did you put in the dask yaml config file?

**Comment by dennissergeev** [comment]
The stdout and stderr are:
<details><summary>dask-worker.o4363862</summary>
============================= PBS epilogue =============================

End of Job Report
Run at 2019-01-07 14:55:22 for job 4363862.xcs00
Submitted              : 2019-01-07 14:53:49
Queued                 : 2019-01-07 14:53:49
Started                : 2019-01-07 14:54:07
Completed              : 2019-01-07 14:55:22
Queued Time            : 0:00:18 (18 seconds)
Elapsed Time           : 0:01:10 (70 seconds, 4% of limit)
Walltime Limit         : 0:30:00 (1800 seconds)
Node Time Limit        : 0:30:00 (1800 seconds)
Node Time              : 0:01:10 (70 seconds, 4% of limit)
Job Name               : dask-worker
Queue                  : normal
Owner                  : deser
Group                  : mo_users
Project                : accacia
Subproject             : 
Funding                : 
Trustzone              : collaboration
STDOUT                 : /home/d03/deser/dask-worker.o4363862
STDERR                 : /home/d03/deser/dask-worker.e4363862
Job Directory          : /scratch/jtmp/pbs.4363862.xcs00.x8z
Job Arch               : XT
CPU Core Type          : broadwell
Total Nodes            : 1
Total Tasks            : 36
Parent Node            : mom15
Parent Node Memory     : 
Parent Node CPU Time   : 
Compute Nodes          : 6809
</details>
<details><summary>dask-worker.e4363862</summary>
distributed.worker - INFO -       Start worker at:   tcp://10.26.24.145:48210
distributed.worker - INFO -          Listening to:   tcp://10.26.24.145:48210
distributed.worker - INFO -              nanny at:         10.26.24.145:58091
distributed.worker - INFO -              bokeh at:         10.26.24.145:36492
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         36  
distributed.worker - INFO -                Memory:                 1000.00 MB
distributed.worker - INFO -       Local Directory: /scratch/jtmp/pbs.4363862.xcs00.x8z/dask-worker-space/worker-lbdo2hc3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.worker - INFO - Waiting to connect to:   tcp://10.168.14.10:60407
distributed.nanny - INFO - Closing Nanny at 'tcp://10.26.24.145:58091'
distributed.worker - INFO - Stopping worker at tcp://10.26.24.145:48210
distributed.dask_worker - INFO - End worker
</details>

and `jobqueue.yaml` contains are:
<details><summary>jobqueue.yaml</summary>
```yaml
jobqueue:
  pbs:
    name: dask-worker

    # Dask worker options
    cores: 36                 # Total number of cores per job
    memory: "10 GB"          # Total amount of memory per job
    processes: 1                # Number of Python processes per job

    interface: null             # Network interface to use like eth0 or ib0
    death-timeout: 60           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: null       # Location of fast local storage like /scratch or $TMPDIR

    # PBS resource manager options
    queue: normal
    project: planets
    walltime: '00:30:00'
    extra: []
    env-extra: []
    resource-spec: null
    job-extra: []
    log-directory: null
```
</details>
