### ISSUE TITLE
PBSCluster is not awaitable

### ISSUE THREAD

**Issue by aidanheerdegen** [dask/dask-jobqueue#273]
It would be great to use `PBSCluster` with `dask-labextension` but for this to work `PBSCluster` has to be able to be used asynchronously, so has to support `await`

https://github.com/dask/dask-labextension/pull/36

When I tried specifying PBSCluster in my `~/.dask/config`:
```yaml
labextension: 
  factory: 
    args: []
    class: PBSCluster
    module: dask_jobqueue
    kwargs: 
      cores: 8
      jobextra: 
        - "-P v45"
      memory: 16GB
      processes: 8
      queue: expressbw
      resource_spec: 'ncpus=8,mem=16G'
```
I got an error:
```
[W 13:05:24.228 LabApp] object PBSCluster can't be used in 'await' expression
```
