### ISSUE TITLE
Allow scheduler_options to be set from config file

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#400]
as mentioned by @kathoef in https://github.com/dask/dask-jobqueue/issues/382#issuecomment-597535146.

My thoughts on this: probably this should be nested inside each cluster-specific section in `~/.config/dask/jobqueue.yaml`. For example, for the `slurm` section this would be something like this:

```
jobqueue:
  slurm:
    name: dask-worker
    walltime: '00:30:00'
    ...

    scheduler_options:
      interface: eth1
      dashboard_address: :8787
```

`dask.config` may just be able to tackle this just fine.
