### ISSUE TITLE
Use environment variables to specify cluster parameters in dask.yaml files

### ISSUE THREAD

**Issue by Ovec8hkin** [dask/dask-jobqueue#406]
Im working on am HPC cluster that is using a SLURM scheduler and have a set of environment variables that specify the queue, project name, number of nodes, and number of cores that I can submit job to. I would like to use these environment variables directly within the dask.yaml file, so that the code is easy to port to other systems.

Is this currently possible?

Example:

I have these environment variables
```
export QUEUENAME=skx-normal
export NUMBER_OF_CORES_PER_NODE=48
export NUMBER_OF_THREADS_PER_CORE=2
```

and I would like to use them like this:

```
jobqueue:
  slurm:
    name: worker-bee
    project: ------
    queue: $QUEUENAME

    cores: $NUMBER_OF_CORES_PER_NODE
    memory: 2GB
    processes: 1

    interface: ib0
    death-timeout: 60           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: $SCRATCH   # Location of fast local storage like /scratch or $TMPDIR

    # LSF resource manager options
    shebang: "#!/usr/bin/env bash"
    walltime: '00:30:00'
    extra: []
    env-extra: []
    ncpus: null
    header-skip: ['--mem', '--cpus-per-task=']

    job-extra: ['-N 2']
    log-directory: null
```
