### ISSUE TITLE
Allow `--mem=0` for unlimited memory on SLURM.

### ISSUE THREAD

**Issue by bollig** [dask/dask-jobqueue#497]
https://github.com/dask/dask-jobqueue/blob/1f9ae1ecc79a5b76930e56c8801f3b8ace659877/dask_jobqueue/slurm.py#L108

For example:
```
    if n >= 1024:
        return "%dK" % math.ceil(n / 1024)
    # Special case in SLURM to allow UNLIMITED memory
    if n == 0:
        return '0'
    return "1K" % n
```

This removes the requirement for SLURM nodes to be configured with RealMemory specified.

**Comment by guillaumeeb** [comment]
Hi @bollig, sorry for the delay, could you propose a PR to solve this issue?

**Comment by bollig** [comment]
Actually, this is a valid workaround at least until SLURM memory tracking is enabled: 

```yaml
# jobqueue.yaml file
jobqueue:
  slurm:
    # Disable memory tracking (AWS ParallelCluster's SLURM does not accept --mem resource by default)
    header_skip: 
      - '--mem'  
    # If header_skip is disabled, memory per job (shared by processes)
    # this satisfies logic in dask-jobqueue/dask_jobqueue/slurm.py  
    memory: 15GB
```
