### ISSUE TITLE
Proposal: `NamedCluster`

### ISSUE THREAD

**Issue by alisterburt** [dask/dask-jobqueue#543]
Hi! First, huge thanks for the work in this repo - it has made working on clusters so easy.

Currently, I must know in advance which type of cluster a user will be running on to decide which `Cluster` object (slurm/sge etc) to instantiate, the appropriate values are then filled from the config file.

Would you consider a PR adding a `NamedCluster` class? The idea is quite simple

- add a `jobqueue-named-clusters` section to the existing cluster config specification
- make `scheduler` a key at the same level as the rest of the entries in existing cluster config

this would look something like

```yml
jobqueue-named:
  my-awesome-cluster:
    scheduler: 'slurm'
    name: dask-worker
    cores: 36                   # Total number of cores per job
    memory: '109 GB'            # Total amount of memory per job
    processes: 9                # Number of Python processes per job
    interface: ib0              # Network interface to use like eth0 or ib0

    queue: regular
    walltime: '00:30:00'
    resource-spec: select=1:ncpus=36:mem=109GB
```

`NamedCluster` would then dispatch to the appropriate `Cluster` class based on the value found in 'scheduler'

The use case I envision is providing daskified programs for non-python users to run in HPC environments - I would be able to use `NamedCluster` liberally in my programs across projects and leave all cluster config to the end user in a config file

**Comment by guillaumeeb** [comment]
Hi @alisterburt,

> Hi! First, huge thanks for the work in this repo - it has made working on clusters so easy.

Thanks, this is always good to have such feedback 😄 

Considering your proposal, this sounds good to me! We should probably discuss the details a bit.

I think we should try if going this way to keep the config file consistent. Perhaps we could just add new entries at the same level as pbs, slurm, etc. ? Those would be kind of default configs or templates. Also, I think we should avoid the `scheduler` term alone that could confuse Dask users, maybe at least `job-scheduler` or `job-scheduling-system`. 

We could have something in the config file like:

```yaml
jobqueue:
  pbs:
    job-scheduling-system: 'pbs' # or have some default in the code?
    name: dask-worker
    
    ...
    
    scheduler-options: {}

  my-awesome-pbs-cluster:
    job-scheduling-system: 'pbs'
    name: dask-worker
    cores: 36                   # Total number of cores per job
    memory: '109 GB'            # Total amount of memory per job
    processes: 9                # Number of Python processes per job
    interface: ib0              # Network interface to use like eth0 or ib0

    queue: regular
    walltime: '00:30:00'
    resource-spec: select=1:ncpus=36:mem=109GB
```
In the end, using `PBSCluster` or `NamedCluster("pbs")` would be the same.

The most important point for this to go through is trying not make the already existing code more complex, to lower maintenance burden.

cc @andersy005 for opinion because there as been work like this at NCAR I think: https://github.com/NCAR/ncar-jobqueue.

**Comment by alisterburt** [comment]
Thank you for the quick turnaround on feedback! 

I'll put together a PR with an implementation using your proposed config structure 🙂

**Comment by jacobtomlinson** [comment]
This proposal sounds really interesting, it's great to hear folks asking for this.

I just want to weigh in and say this is exactly the kind of thing we are trying to solve with [dask-ctl](https://dask-ctl.readthedocs.io/en/latest/spec.html) and we already have a similar feature over there. For any cluster manager that supports `dask-ctl` you can create a YAML spec file and create the cluster from the command line. @ian-r-rose and I have also been discussing replacing the cluster spawning tooling in the Jupyter Lab Extension with this.

I would caution against implementing this in `dask-jobqueue` and instead suggest that we add `dask-ctl` support to `dask-jobqueue` and reuse the functionality from there.

What do you think @alisterburt, @guillaumeeb?

**Comment by alisterburt** [comment]
@jacobtomlinson thanks for your input! 

If there's an ongoing dask project which aims to support the same functionality that's clearly the better option, I'll take a look at `dask-ctl` now and look into adding support here

**Comment by alisterburt** [comment]
@jacobtomlinson `dask-ctl` is exactly what I was looking for and I *love* that it means I'm not limited to only HPC environments. If @guillaumeeb agrees I will push on and attempt to add `dask-ctl` support to `dask-jobqueue`

If I run into issues am I okay to ping you @jacobtomlinson ? This is deeper than I've previously been in the dask internals 🙃

**Comment by jacobtomlinson** [comment]
@alisterburt awesome! Yep happy to help.

I suspect adding support here will be non-trivial due to a lack of metadata storage in HPC scheduling systems. A good area to focus might be to bring the `daskctl create` functionality to Python with a goal to support the functionality you outlined above. Perhaps save discovery for later.

**Comment by jacobtomlinson** [comment]
Actually after re-reading the OP here and looking at `dask-ctl` I think much of the above use case is already satisfied.

```yaml
# /path/to/spec.yaml
version: 1
module: "dask_jobqueue"
class: "SLURMCluster"
args: []
kwargs:
  name: dask-worker
  cores: 36                   # Total number of cores per job
  memory: '109 GB'            # Total amount of memory per job
  processes: 9                # Number of Python processes per job
  interface: ib0              # Network interface to use like eth0 or ib0

  queue: regular
  walltime: '00:30:00'
  resource-spec: select=1:ncpus=36:mem=109GB
```

```python
from dask_ctl import create_cluster

cluster = create_cluster("/path/to/spec.yaml")
```

The main difference here being that `dask-ctl` expects you to provide a path to a YAML file instead of loading from the Dask config.

Exploring supporting the rest of the `dask-ctl` feature set would be really nice to have here, but not necessary to satisfy this issue. I'll open a new issue to track this.

Therefore I propose we close out this issue as resolved.
