### ISSUE TITLE
Reorganize the dask-jobqueue config file

### ISSUE THREAD

**Issue by jhamman** [dask/dask-jobqueue#68]
It is not unheard of to have multiple job queue systems running from the machine. For example, the machine I use the most, Cheyenne, uses both PBS and Slurm. For cases like this, it would be nice if we revamped our config file stricture a bit.

Currently we have:

```yml
jobqueue:
  name: dask-worker
  threads: 2
  processes: 4
  memory: 8GB
  interface: null
  death-timeout: 60
  local-directory: null
  extra: ""
  env-extra: []

  queue: null
  project: null
  walltime: '00:30:00'

  pbs:
    resource-spec: null
    job-extra: []

  sge:
    resource-spec: null

  slurm:
    job-cpu: null
    job-mem: null
    job-extra: {}
```

I'd like to propose that we move some of the jobqueue values into the pbs/sge/slurm catagories:

```yml
jobqueue:
  # dask options
  name: dask-worker
  death-timeout: 60

  pbs:
    threads: 2
    processes: 4
    memory: 8GB
    interface: null
    local-directory: null
    extra: ""
    env-extra: []
    queue: null
    project: null
    walltime: '00:30:00'
    resource-spec: null
    job-extra: []

  sge:
    threads: 2
    processes: 4
    memory: 8GB
    interface: null
    local-directory: null
    extra: ""
    env-extra: []
    queue: null
    project: null
    walltime: '00:30:00'
    resource-spec: null

  slurm:
    threads: 2
    processes: 4
    memory: 8GB
    interface: null
    local-directory: null
    extra: ""
    env-extra: []
    queue: null
    project: null
    walltime: '00:30:00'

    job-cpu: null
    job-mem: null
    job-extra: {}
```

**Comment by mrocklin** [comment]
We might also consider having separate yaml files `sge.yaml`, `slurm.yaml`, `pbs.yaml`

**Comment by jhamman** [comment]
That would also be a reasonable choice. Open to ideas here.

**Comment by mrocklin** [comment]
I'm currently in favor of separate files

**Comment by jhamman** [comment]
I'm fine with separate files. @lesteve and @guillaumeeb, any thoughts here?

**Comment by guillaumeeb** [comment]
I don't have a strong opinion on this. If separated files, we should still keep some 'jobqueue' prefix, don't you think?
What wilç be the impaxt in the code? Each Cluster implementation will use all the keywords by default?

**Comment by mrocklin** [comment]
Can you expand on your thoughts about why we should keep the jobqueue
prefix?

**Comment by guillaumeeb** [comment]
I just find it weird to have a `.config/dask` directory that looks like this: 
```
distributed.yaml
dask.yaml
pbs.yaml
sge.yaml
```

I would prefer a more explicit naming (and more consistent with other packages):
```
distributed.yaml
dask.yaml
jobqueue-pbs.yaml
jobqueue-sge.yaml
```

**Comment by mrocklin** [comment]
OK, no objection from me

**Comment by mrocklin** [comment]
Hrm, in trying to do this we now have to repeat all keyword arguments in all constructors.  Are we ok with this?  Also, what should we do for things like MOAB?

**Comment by mrocklin** [comment]
I'm also now against the idea of splitting into multiple files, especially as more job schedulers come online.

**Comment by jhamman** [comment]
What if we implemented some basic inheritance?

**Comment by mrocklin** [comment]
Sorry, let me be more explicit.  Currently the core superclass constructor looks like this

```python
class JobQueueCluster(Cluster):
    def __init__(self,
                 name=dask.config.get('jobqueue.name'),
                 threads=dask.config.get('jobqueue.threads'),
                 processes=dask.config.get('jobqueue.processes'),
                 memory=dask.config.get('jobqueue.memory'),
                 interface=dask.config.get('jobqueue.interface'),
                 death_timeout=dask.config.get('jobqueue.death-timeout'),
                 local_directory=dask.config.get('jobqueue.local-directory'),
                 extra=dask.config.get('jobqueue.extra'),
                 env_extra=dask.config.get('jobqueue.env-extra'),
                 **kwargs
                 ):
        """ """
```

If we now have separate config values for each resource manager then our current use of inheritance becomes less useful.  Probably we'll get default values at runtime rather than import time, which is probably fine.

**Comment by mrocklin** [comment]
So we would have something like the following:

```python
class JobQueueCluster(Cluster):
    def __init__(self,
                 name=None,
                 threads=None
                 processes=None,
...
                 **kwargs
                 ):

        if name is None:
            name = dask.config.get('jobqueue.%s.name' % self._config_name)
        if ...
```

**Comment by guillaumeeb** [comment]
Yep, I agree that we should not split the config into multiple files in the end.

What @mrocklin was saying earlier was also what I was affraid of, I don't really like the idea of repeating all the keywords into each subclass `__init__`. The last proposed solution seems much better though, even if it add some complexity, it does take advantage of inheritance.

Rather than `_config_name`, we could use `_scheduler_name`, which might be usefull in the future for other purpose (or not ...).

We should also clearly define what goes into the pbs/slurm/sge categories, all of the values? Or should we keep some in the jobqueue level?

I personnaly have no use of this functionnality, and I believe (but I may be wrong) that this is true for most users. But the current proposed solution is not too intrusive into the scheduler subclass code, and replacing 

```yaml
jobqueue:
  name: dask-worker
  threads: 2
  processes: 4
  memory: 8GB
  interface: null
  death-timeout: 60
  local-directory: null
  extra: ""
  env-extra: []

  queue: null
  project: null
  walltime: '00:30:00'

  pbs:
    resource-spec: null
    job-extra: []
```

By

```yaml
jobqueue:
  # dask options
  name: dask-worker
  death-timeout: 60

  pbs:
    threads: 2
    processes: 4
    memory: 8GB
    interface: null
    local-directory: null
    extra: ""
    env-extra: []
    queue: null
    project: null
    walltime: '00:30:00'
    resource-spec: null
    job-extra: []
```

in my config file is fine for me.
