### ISSUE TITLE
Named configurations as an option to cluster constructors

### ISSUE THREAD

**Issue by josephhardinee** [dask/dask-jobqueue#95]
Would there be interest in having named configuration sets for the different constructors in addition to the pbs and slurm (and other) default configuration sets? 

Use Case
----------
There are several use cases. The first is clusters that share filesystems between different scheduling systems (Cori and Edison on NERSC). The second would be supporting multiple queues (high_mem, debug, burst, scavenger, etc). This would allow you to have different configuration sets for different job types. 

Implementation
----------------
Currently when issuing a `PBSCluster()` call, the configuration is drawn from the 
jobqueue.pbscluster dictionary inside yaml. The proposed implementation would leave that alone, but would add a optional keyword `scheduler_name`. 
The user could then call 
```python
cluster = PBSCluster(scheduler_name='high_mem')
```

to access the portion of the yaml file given by the high_mem option 

```yaml
jobqueue:
    high_mem:
        cores: 64
        memory: 128GB
        processes: 4
        queue: debug
        walltime: '00:10:00'
        job-extra: ['-C haswell', '-L project, SCRATCH, cscratch1']
    pbs:
        cores: 64
        memory: 128GB
        processes: 4
        queue: debug
        walltime: '00:10:00'
        job-extra: ['-C haswell', '-L project, SCRATCH, cscratch1']
```
The keyword would default to the original pbs(or slurm, etc). 

The implementation is pretty straightforward, just have each of the cluster initiation objects set self.scheduler_name to optional parameter scheduler name. Then change each of the `dask.config.get` calls to use scheduler_name instead of their hardcoded values. 

If everyone is okay with this I can submit a PR next week with the implementation for comment.
